/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.TipoDocumentoDAO;
import entity.TipoDocumento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import view.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author elder_benites
 */
public class TelaTipoDocumento extends javax.swing.JDialog {

    TipoDocumento objTipoDocumento = new TipoDocumento();
    List<TipoDocumento> lista = new ArrayList<TipoDocumento>();

    /**
     * Creates new form TelaTipo
     */
    public TelaTipoDocumento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        atualizarTabelaTipoDocumento();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisarTipos = new javax.swing.JTextField();
        btnNovoTipos = new javax.swing.JButton();
        btnAlterarTipos = new javax.swing.JButton();
        btnExcluirTipos = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTiposDocumentos = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos de Documento");

        jLabel1.setText("Pesquisar Tipos de Documentos:");

        txtPesquisarTipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarTiposKeyReleased(evt);
            }
        });

        btnNovoTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/New document.png"))); // NOI18N
        btnNovoTipos.setText("Novo");
        btnNovoTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTiposActionPerformed(evt);
            }
        });

        btnAlterarTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Modify.png"))); // NOI18N
        btnAlterarTipos.setText("Alterar");
        btnAlterarTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarTiposActionPerformed(evt);
            }
        });

        btnExcluirTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        btnExcluirTipos.setText("Excluir");
        btnExcluirTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTiposActionPerformed(evt);
            }
        });

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lstTiposDocumentos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstTiposDocumentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnNovoTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAlterarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluirTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarTipos)
                    .addComponent(btnVoltar)
                    .addComponent(btnExcluirTipos)
                    .addComponent(btnNovoTipos))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTiposActionPerformed

        objTipoDocumento.setDescricao(JOptionPane.showInputDialog("Informe o novo tipo de documento:"));

        TipoDocumentoDAO dao = new TipoDocumentoDAO();
        dao.insert(objTipoDocumento);
        atualizarTabelaTipoDocumento();

    }//GEN-LAST:event_btnNovoTiposActionPerformed

    private void btnAlterarTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarTiposActionPerformed
//recebe objeto inteiro
        objTipoDocumento = (TipoDocumento) lstTiposDocumentos.getSelectedValue();
        objTipoDocumento.setDescricao(JOptionPane.showInputDialog("Informe a alteração do tipo de documento:", objTipoDocumento.getDescricao()));

        TipoDocumentoDAO dao = new TipoDocumentoDAO();
        dao.update(objTipoDocumento);

        atualizarTabelaTipoDocumento();


    }//GEN-LAST:event_btnAlterarTiposActionPerformed

    private void btnExcluirTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTiposActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este tipo de documento:");
        if (confirmacao == 0) {

            objTipoDocumento = (TipoDocumento) lstTiposDocumentos.getSelectedValue();

            TipoDocumentoDAO dao = new TipoDocumentoDAO();
            dao.delete(objTipoDocumento.getIdTipodeDocumento());

            this.atualizarTabelaTipoDocumento();
        }

    }//GEN-LAST:event_btnExcluirTiposActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPesquisarTiposKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarTiposKeyReleased
        DefaultListModel model = new DefaultListModel();
        for (TipoDocumento tipoDocumento : lista) {
            if (tipoDocumento.getDescricao().startsWith(txtPesquisarTipos.getText())) {
                model.addElement(tipoDocumento);
            }
        }
        lstTiposDocumentos.setModel(model);
    }//GEN-LAST:event_txtPesquisarTiposKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTipoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTipoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTipoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTipoDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaTipoDocumento dialog = new TelaTipoDocumento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarTipos;
    private javax.swing.JButton btnExcluirTipos;
    private javax.swing.JButton btnNovoTipos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstTiposDocumentos;
    private javax.swing.JTextField txtPesquisarTipos;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabelaTipoDocumento() {

        TipoDocumentoDAO dao = new TipoDocumentoDAO();
        lista = dao.listarTipoDocumento();

        DefaultListModel model = new DefaultListModel();

        for (TipoDocumento tipoDocumento : lista) {
            model.addElement(tipoDocumento);
        }

        lstTiposDocumentos.setModel(model);

    }
}
