/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.EmpresaDAO;
import dao.ProtocoloDAO;
import dao.TipoDocumentoDAO;
import dao.UsuarioDAO;
import entity.Empresa;
import entity.Protocolo;
import entity.TipoDocumento;
import entity.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VDISOO0219
 */
public class TelaProtocolo extends javax.swing.JDialog {

    /**
     * Creates new form TelaProtocolo
     */
    public TelaProtocolo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        UsuarioDAO daoUsuario = new UsuarioDAO();
        EmpresaDAO daoEmpresa = new EmpresaDAO();
        TipoDocumentoDAO daoTipoDocumento = new TipoDocumentoDAO();

        List<Usuario> listaUsuarios = daoUsuario.listarUsuarios();
        for (Usuario usuario : listaUsuarios) {
            cbResponsavelCadastro.addItem(usuario);
            cbResponsavelEstocagem.addItem(usuario);
            cbResponsavelSeparacao.addItem(usuario);
        }

        List<Empresa> listaEmpresas = daoEmpresa.listarEmpresas();
        for (Empresa empresa : listaEmpresas) {
            cbEmpresa.addItem(empresa);
        }

        List<TipoDocumento> listaTipoDocumentos = daoTipoDocumento.listarTipoDocumento();
        for (TipoDocumento tipoDocumento : listaTipoDocumentos) {
            cbTipoDocumento.addItem(tipoDocumento);
        }
        geraProtocolo();
    }
    Protocolo objProtocolo = new Protocolo();
    ProtocoloDAO daoProtocolo = new ProtocoloDAO();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        lblNumeroProtocolo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQuantidadeDocumentos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtResponsavelEntrega = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox();
        cbResponsavelEstocagem = new javax.swing.JComboBox();
        cbResponsavelSeparacao = new javax.swing.JComboBox();
        cbResponsavelCadastro = new javax.swing.JComboBox();
        rbtnEntrada = new javax.swing.JRadioButton();
        rbtnSaida = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        txtHorario = new javax.swing.JFormattedTextField();
        ftxtCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerar protocolo E/S"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/OK.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 303, 100, -1));

        lblNumeroProtocolo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNumeroProtocolo.setForeground(new java.awt.Color(255, 0, 51));
        jPanel4.add(lblNumeroProtocolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, 130, 14));

        jLabel7.setText("Data e Hora:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 184, -1, -1));

        jLabel9.setText("Páginas:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 145, -1, -1));
        jPanel4.add(txtQuantidadeDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 142, 152, -1));

        jLabel10.setText("Responsável Cadastro:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 104, -1, -1));

        jLabel11.setText("Responsável Estocagem:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 185, -1, -1));

        jLabel12.setText("Responsável Separação:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 145, -1, -1));

        jLabel13.setText("Tipo do Documento:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 63, -1, -1));

        jPanel4.add(cbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 59, 152, 23));

        jLabel14.setText("Responsável Entrega:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 224, -1, -1));
        jPanel4.add(txtResponsavelEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 221, 300, -1));

        jLabel15.setText("CPF:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 262, -1, -1));

        jLabel16.setText("Empresa:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 63, -1, -1));

        jPanel4.add(cbEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 59, 300, -1));

        jPanel4.add(cbResponsavelEstocagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 141, 300, -1));

        jPanel4.add(cbResponsavelSeparacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 300, -1));

        jPanel4.add(cbResponsavelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 181, 300, -1));

        buttonGroup1.add(rbtnEntrada);
        rbtnEntrada.setSelected(true);
        rbtnEntrada.setText("Entrada");
        jPanel4.add(rbtnEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 100, -1, -1));

        buttonGroup1.add(rbtnSaida);
        rbtnSaida.setText("Saída");
        jPanel4.add(rbtnSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 100, -1, -1));

        jLabel8.setText("Protocolo:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 104, -1, -1));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel4.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 303, 97, -1));

        try {
            txtHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 181, 152, -1));

        try {
            ftxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCpf.setText("   .   .   -  ");
        jPanel4.add(ftxtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 259, 300, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtQuantidadeDocumentos.getText().equals("") || ftxtCpf.getText().equals("")
                || txtResponsavelEntrega.getText().equals("") || txtHorario.getText().equals("")) {

            JOptionPane.showMessageDialog(rootPane, "Por favor preencha todos os campos!");

        } else {

            objProtocolo.setEmpresa((Empresa) cbEmpresa.getSelectedItem());
            objProtocolo.setResponsavelCadastro((Usuario) cbResponsavelCadastro.getSelectedItem());
            objProtocolo.setResponsavelSeparacao((Usuario) cbResponsavelSeparacao.getSelectedItem());
            objProtocolo.setResponsavelEstocagem((Usuario) cbResponsavelEstocagem.getSelectedItem());
            objProtocolo.setResponsavelEntrega(txtResponsavelEntrega.getText());
            objProtocolo.setCpf(ftxtCpf.getText());
            objProtocolo.setTipoDocumento((TipoDocumento) cbTipoDocumento.getSelectedItem());
            objProtocolo.setTipoProtocolo(tipoProtocolo());
            objProtocolo.setQuantidadeDocumento(Integer.parseInt(txtQuantidadeDocumentos.getText()));
            objProtocolo.setNumeroProtocolo(Integer.parseInt(lblNumeroProtocolo.getText()));
            try {

                objProtocolo.setDataHora(formatador.parse(txtHorario.getText() + ":00"));

            } catch (ParseException ex) {
                Logger.getLogger(TelaProtocolo.class.getName()).log(Level.SEVERE, null, ex);
            }

            daoProtocolo.insert(objProtocolo);

            JOptionPane.showMessageDialog(rootPane, "Salvo com Sucesso!!");
            limparCampos();
            geraProtocolo();

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    public int tipoProtocolo() {

        if (rbtnEntrada.isSelected()) {
            return 0;

        }

        return 1;
    }

    public void limparCampos() {
        txtResponsavelEntrega.setText(null);
        ftxtCpf.setText(null);
        txtHorario.setText(null);
        txtQuantidadeDocumentos.setText(null);
        cbEmpresa.setSelectedIndex(1);
    }

    public void geraProtocolo() {
        int labelProtocolo = 0;
        ProtocoloDAO pDAO = new ProtocoloDAO();
        List<Protocolo> listaVerifica = pDAO.listarNumeroProtocolos();
        int protocolo = pDAO.pegaNumeroProtocolo();

        if (protocolo == 0) {
            labelProtocolo = 20150001;
            lblNumeroProtocolo.setText(labelProtocolo + "");
        } else {

            if (lblNumeroProtocolo.getText().equals("")) {
                lblNumeroProtocolo.setText(verificaLabelProtocolo(listaVerifica));

            } else {

                labelProtocolo = Integer.parseInt(lblNumeroProtocolo.getText());
                labelProtocolo++;
                lblNumeroProtocolo.setText(labelProtocolo + "");
            }

        }

    }

    public String verificaLabelProtocolo(List<Protocolo> listaProtocolo) {
        String pegaNumero = "";

        for (Protocolo protocolo : listaProtocolo) {

            pegaNumero = 1 + protocolo.getNumeroProtocolo() + "";
        }

        return pegaNumero;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProtocolo dialog = new TelaProtocolo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbEmpresa;
    private javax.swing.JComboBox cbResponsavelCadastro;
    private javax.swing.JComboBox cbResponsavelEstocagem;
    private javax.swing.JComboBox cbResponsavelSeparacao;
    private javax.swing.JComboBox cbTipoDocumento;
    private javax.swing.JFormattedTextField ftxtCpf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNumeroProtocolo;
    private javax.swing.JRadioButton rbtnEntrada;
    private javax.swing.JRadioButton rbtnSaida;
    private javax.swing.JFormattedTextField txtHorario;
    private javax.swing.JTextField txtQuantidadeDocumentos;
    private javax.swing.JTextField txtResponsavelEntrega;
    // End of variables declaration//GEN-END:variables
}
